# Generated by Django 4.2.4 on 2023-11-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixlpix', '0002_userprofile_following_alter_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
